// Round 2 guides — owner-requested angles: the SPEED of claim removal (our
// selling point), "is this music AI or a real composer" (our selling point), and
// how to pick music for a project (the funnel into the catalogue / future AI
// search). Kept in its own file so the guide list stays easy to extend.
//
// PURE DATA ONLY (no React, no "@/" alias) — imported by the app AND by the
// Cloudflare edge prerender.

import type { Guide } from "./guides";

export const guidesRound2: Guide[] = [
  {
    slug: "how-to-remove-a-content-id-claim",
    title: "How to Remove a Content ID Claim on YouTube (and How Long It Takes)",
    h1: "How do I remove a Content ID claim, and how long does it take?",
    description:
      "Step by step: what to do when a Content ID claim appears on licensed music, how long each route takes, and how to make sure it never happens again.",
    tldr:
      "Go to the library that licensed you the music — not to YouTube's dispute form. Send them the video URL and your license or account reference and ask them to release the claim. With TV Music Store, a claim on a licensed use is sent for release within one business day. Disputing through YouTube alone can take up to 30 days, because YouTube gives the claimant that long to respond.",
    updated: "2026-07-11",
    readMinutes: 4,
    sections: [
      {
        heading: "The two routes, and why one is much slower",
        table: {
          headers: ["Route", "What happens", "Typical time"],
          rows: [
            [
              "Ask the library (right way)",
              "They confirm your license and send the release straight through the Content ID system",
              "Request goes out within one business day with us",
            ],
            [
              "Dispute inside YouTube Studio",
              "YouTube forwards the dispute; the claimant has up to 30 days to respond",
              "Days to 30 days",
            ],
          ],
        },
      },
      {
        heading: "What to send the library",
        bullets: [
          "The video URL — an unlisted or private link is fine.",
          "The track title, and the version if you used an alternate cut.",
          "Your account email or the License Number from the license document.",
          "Your channel URL — if the library offers channel whitelisting, ask in the same message so it never repeats.",
        ],
      },
      {
        heading: "Do not do these",
        bullets: [
          "Do not delete and re-upload the video — you lose the views and the claim comes back.",
          "Do not dispute with \"I bought the music\" and no reference. An unsupported dispute is slow and can be rejected.",
          "Do not mute the audio in a panic. The claim is not a strike; the video is safe while it is being cleared.",
        ],
      },
      {
        heading: "The fastest route: report it where you licensed it",
        paragraphs: [
          "Some libraries let you register channels for monitoring; all serious ones release claims on licensed uses when you report them. Either way, the library — not YouTube's dispute form — is the short path, because the library can confirm your license instantly.",
          "On TV Music Store, paste the video link in your account (Copyright Claims) and name the track — the claim is sent for release within one business day. And publish first — a private video is invisible to YouTube's API, so nobody can act on a claim on it.",
        ],
      },
    ],
    faq: [
      {
        q: "How long does it take to remove a Content ID claim?",
        a: "Through the library that licensed you the track it is fast: TV Music Store sends a claim on a licensed use for release within one business day, and the release then runs through the Content ID system, usually within a day. Through YouTube's own dispute process the claimant has up to 30 days to answer, so it can take weeks.",
      },
      {
        q: "Does the claim hurt my channel while it is open?",
        a: "No. A Content ID claim is not a copyright strike. Your channel standing is untouched; only the monetization of that one video can be affected until it is released.",
      },
      {
        q: "Will the claim come back on the next video?",
        a: "It can — releasing a claim only handles the video it was raised on. Report each claimed video the same way; the request takes a minute and goes out within one business day.",
      },
      {
        q: "Can I speed up a YouTube dispute?",
        a: "Not from your side. That is exactly why you contact the library instead — they can release the claim directly, without the 30-day window.",
      },
    ],
    related: ["content-id-claims-explained", "royalty-free-music-for-youtube"],
  },
  {
    slug: "ai-music-vs-human-composed",
    title: "AI Music vs Human-Composed Music: How to Tell, and Why It Matters",
    h1: "How can I tell if a track was written by a human or generated by AI?",
    description:
      "AI-generated music is flooding stock libraries. How to spot it, why detector tools are unreliable, and the one signal that actually holds up: a named, registered composer.",
    tldr:
      "Often you cannot tell by listening any more, and AI-detection tools produce both false positives and false negatives — so \"it sounds human\" is not evidence. The signal that holds up is provenance: a named composer with a real registration (PRO and IPI number), a body of work, and cue-sheet data you can file with a broadcaster. Generated tracks have none of that, which is also why they cause trouble at broadcast delivery. Every track on TV Music Store is written by a credited human composer with that paperwork behind it.",
    updated: "2026-07-11",
    readMinutes: 5,
    sections: [
      {
        heading: "What still gives AI music away — sometimes",
        bullets: [
          "Structure that never argues with itself: a motif repeats without gradual intensification, and nothing unexpected ever happens.",
          "Harmonic default settings: the same handful of progressions, because that is what the training data rewards.",
          "Emotionally flat despite being technically clean — precise, but it never breathes.",
          "Suspicious output volume: an \"artist\" who released two hundred tracks in four months is not a person.",
        ],
      },
      {
        heading: "Why detector tools are not the answer",
        paragraphs: [
          "AI-music detectors exist and they are improving, but none is reliable enough to bet a delivery on: they flag human recordings as AI and pass AI recordings as human. Using one as proof, in either direction, is a bad idea.",
          "The line is also blurrier than the question assumes. A human composer who used an AI tool to sketch a string layer is not the same thing as a fully generated track — and no detector distinguishes those cases.",
        ],
      },
      {
        heading: "The check that actually works: provenance",
        table: {
          headers: ["Question", "Human-composed catalogue", "Generated track"],
          rows: [
            ["Is there a named composer?", "Yes — with an artist page and a body of work", "Usually a pseudonym with no history"],
            ["Registered with a PRO (BMI/ASCAP/PRS)?", "Yes, with an IPI/CAE number", "Typically not"],
            ["Can you file a cue sheet with it?", "Yes — the data is on the license", "No — there is nobody to pay"],
            ["Will a broadcaster accept the delivery?", "Yes", "It becomes your problem at delivery"],
          ],
        },
      },
      {
        heading: "Why this is not just a matter of taste",
        paragraphs: [
          "If your project goes to television, a streaming platform or a festival, you must deliver a cue sheet naming the composer, their PRO and their IPI number. Music with no registered author cannot be filed. Nobody warns you about this at download time — you find out at delivery, when the schedule is tight.",
          "It matters for the money too: performance royalties are paid to registered composers. Generated tracks produce no such registration, and the ownership of AI output is still being argued over in several territories.",
        ],
      },
      {
        heading: "Where we stand",
        paragraphs: [
          "TV Music Store is a boutique catalogue of music written by human composers. Every track has a named composer, an artist page, and cue-sheet data — legal name, PRO and IPI — printed on the license you receive. That is not a marketing claim you have to trust; it is paperwork you can check and file.",
        ],
      },
    ],
    faq: [
      {
        q: "Can an AI detector prove that music is human-made?",
        a: "No. Current detectors produce both false positives and false negatives, so they cannot serve as proof in either direction. Provenance — a named, PRO-registered composer — is the reliable signal.",
      },
      {
        q: "Is AI-generated music legal to use in a commercial video?",
        a: "It depends on the platform's terms and on your jurisdiction, and the ownership of AI output is still unsettled in several territories. The practical problem arrives earlier: broadcasters and streaming platforms need a cue sheet with a registered composer, which generated music cannot provide.",
      },
      {
        q: "Is the TV Music Store catalogue AI-generated?",
        a: "No. Every track is written by a credited human composer with PRO/IPI registration and a public artist page.",
      },
    ],
    related: ["sync-licensing-and-cue-sheets", "music-for-documentary-films"],
  },
  {
    slug: "how-to-choose-music-for-your-project",
    title: "How to Choose the Right Music for Your Video (a 5-Minute Method)",
    h1: "How do I choose the right music for my project?",
    description:
      "Stop auditioning tracks at random. A short, repeatable method: define the job the music has to do, search by use case rather than genre, and test against the cut.",
    tldr:
      "Do not start from genre — start from the job. Write one sentence: what the video is, who watches it, and what they should feel at the end. That sentence gives you the three filters that matter: use case (trailer, documentary, advertising…), mood (hopeful, tense, powerful…) and pace. Search on those, shortlist three tracks, and audition each against the actual cut with the dialogue in — never in silence. The track that disappears behind the picture is the right one.",
    updated: "2026-07-11",
    readMinutes: 4,
    sections: [
      {
        heading: "Step 1 — write the brief in one sentence",
        paragraphs: [
          "\"A two-minute brand film for a construction company, shown at a trade fair, and it should feel confident and modern, not epic.\" That is enough. The sentence already contains the use case (business), the mood (confident, modern) and what to avoid (epic).",
          "Most bad music choices come from skipping this step: people search for a genre they personally like instead of the job the music has to do.",
        ],
      },
      {
        heading: "Step 2 — filter by use case, not genre",
        bullets: [
          "Use case first — it encodes the job: Advertising, Documentary, Movie Trailer, Business, Video Game.",
          "Mood second — the emotional target from your sentence.",
          "Genre last, and mostly to exclude what you know is wrong.",
          "Tempo and length: match the pace of the edit, not the pace of the music you like.",
        ],
      },
      {
        heading: "Step 3 — audition against the picture, with dialogue",
        paragraphs: [
          "A track that is thrilling on its own often fights the voice. Drop your three candidates under the actual cut, at the actual level, with the dialogue playing. Two of them will suddenly be obviously wrong.",
          "Watch the build: does the music peak where your point lands? A cue that peaks four seconds late will fight you for the whole edit.",
        ],
      },
      {
        heading: "Step 4 — check the license before you fall in love",
        bullets: [
          "Is it going into a paid ad, a client's project or a broadcast? Then the tier matters — check it before you cut to the track.",
          "Will the edit be re-timed? Take the stems.",
          "Are there alternate versions (short cut, underscore, no-drums)? They save the edit later.",
        ],
      },
      {
        heading: "A shortcut we are building",
        paragraphs: [
          "We are adding a search that takes the brief sentence itself — describe the project in plain language and get a shortlist back, instead of clicking through filters. Until then, the tag pages (browse by mood, genre and use case) are the fastest route: they are built from exactly these three axes.",
        ],
      },
    ],
    faq: [
      {
        q: "Should I pick music by genre?",
        a: "Genre is the last filter, not the first. Start from the use case (what the video is for) and the mood you want the viewer to leave with.",
      },
      {
        q: "How do I know a track fits before I buy it?",
        a: "Audition it against your actual cut with the dialogue playing, not in silence. Preview the full track, not just the exciting ten seconds.",
      },
      {
        q: "How many tracks should I shortlist?",
        a: "Three. More than that and you are auditioning music instead of editing; fewer and you have not tested the idea.",
      },
    ],
    related: ["trailer-music-guide", "music-for-ads-and-commercials", "how-much-does-royalty-free-music-cost"],
  },
];
